- name: Import CodiMD Helm repository
  kubernetes.core.helm_repository:
    name: "{{ codimd_helm_repo_name }}"
    repo_url: "{{ codimd_helm_repo_url }}"

- name: Deploy CodiMD with Helm
  kubernetes.core.k8s:
    state: present
    definition: "{{ item }}"
  with_items: >-
    {{ 
      lookup('template', 'k8s-template-codimd.yml') |
      from_yaml_all 
    }}
